name: phpunit

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  run-tests:
    strategy:
      matrix:
        operating-system: [ubuntu-latest, windows-latest, macos-latest]
        php-versions: [
          '7.3',
#          '7.4',
#          '8.0',
        ]

    runs-on: ${{ matrix.operating-system }}

    name: PHP ${{ matrix.php-versions }} Test on ${{ matrix.operating-system }}

    steps:
      - name: Php version
        run: 'php -v'

#      - name: Git status
#        run: 'git status'

      - name: Current dirrectory
        run: 'pwd'

#      - name: Files list
#        run: 'ls -lah'

      - name: Repository
        run: 'echo ${{ github.repository }}'

      - name: Test
        run: 'echo $@'

#      - name: Checkout
#        uses: actions/checkout@v2
