name: phpunit

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  run-tests:
    strategy:
      matrix:
        operating-system: [ubuntu-latest, windows-latest, macos-latest]
        php-versions: [
          '7.3',
#          '7.4',
#          '8.0',
        ]

    runs-on: ${{ matrix.operating-system }}

    name: PHP ${{ matrix.php-versions }} Test on ${{ matrix.operating-system }}

    steps:
      - name: Php version
        run: 'php -v'
      - name: Php7.3 version
        run: 'php7.3 -v'
      - name: Php7.4 version
        run: 'php7.4 -v'
      - name: Php8.0 version
        run: 'php8.0 -v'

      - name: Checkout
        run: |
          echo "$ git init"
          git init
          echo "$ git remote add origin https://github.com/${{ github.repository }}"
          git remote add origin https://github.com/${{ github.repository }}
          echo "$ git fetch --no-tags --prune --depth=1 origin +${{ github.sha }}:${{ github.ref }}"
          git fetch --no-tags --prune --depth=1 origin +${{ github.sha }}:${{ github.ref }}
          echo "$ git checkout --progress --force ${{ github.sha }}"
          git checkout --progress --force ${{ github.sha }}
          echo "$ git status"
          git status
          echo "$ git log -1"
          git log -1
